### ISSUE TITLE
No radare logo in the main page at some specific window sizes

### ISSUE THREAD

**Issue by radare** [radareorg/radareorg#46]
<img width="1421" alt="screen shot 2018-05-05 at 11 07 26" src="https://user-images.githubusercontent.com/917142/39661686-0aec451a-5056-11e8-9729-9cee86a0fbf1.png">

**Comment by pawlos** [comment]
this is due to usage of Alabaster theme and one of its rules:

_static/alabaster.css

    @media screen and (max-width: 875px) {
    ....
    div.sphinxsidebar p.logo {
        display: none;
    }

IMO this is a normal practice to hide a logo for mobile (as screen estate is limited) and a hamburger-menu is displayed instead. One problem with this is that there's no link to the main page as in the desktop view this is being done by clicking on logo itself.

**Comment by jvoisin** [comment]
I'm with @pawlos on this one, there is no need for a logo. Worst case, someone can always add a small logo floating on the top-right of the page.
